name: Run Selenium Tests

on:
  repository_dispatch:
    types: [webapp_updated]
  workflow_dispatch: # Allows manual triggering directly from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify payload data (Optional)
        run: |
          echo "Triggered by branch: ${{ github.event.client_payload.branch }}"
          echo "Commit SHA: ${{ github.event.client_payload.commit_sha }}"

      - name: Run Selenium Tests
        env:
          BASE_URL : https://muhammadsyifaaul.github.io/webapp-demo/
        run: |
          pytest test_webapp.py -v -s
